# Language to be used, if you do not know what you are doing, leave this as en_us.
#
#    To display English: en_us
#        https://github.com/Hinogo2210/ContainerView/blob/main/src/main/resources/lang/en_us.yml
#    Para mostrar español: es_es
#        https://github.com/Hinogo2210/ContainerView/blob/main/src/main/resources/lang/es_es.yml
#    顯示繁體中文(香港): zh_hk
#        https://github.com/Hinogo2210/ContainerView/blob/main/src/main/resources/lang/zh_hk.yml
#    显示简体中文(中国大陆): zh_cn
#        https://github.com/Hinogo2210/ContainerView/blob/main/src/main/resources/lang/zh_cn.yml
#
# PM me on discord to add your language: mromango
language: en_us

# Based on the player's location and specified half-width (int range),
# this function returns a list of blocks within the cuboid-shaped area centered on the player.
# The cuboid extends from the player's position in all directions (x, y, z) by the specified range.
view_range: 10

# How much second(s) will containers glow and maintain viewable in a single view session.
view_session_duration: 30

# Should the view gui automatically close when time is up.
gui_auto_close: true

# Viewable container.
# Available containers: CHEST, DISPENSER, DROPPER, BARREL, SHULKER_BOX, TRAPPED_CHEST.
containers:
  - CHEST
  - DISPENSER
  - DROPPER
  - BARREL
  - SHULKER_BOX
  - TRAPPED_CHEST

  # !!!!!!!!!!!!!!!!!!!!!!! #
  # Because there are only 16 colors for the glow effect,
  # the amount of color(s) below will determine how many containers you can view at a time. (Max 16)
  # !!!!!!!!!!!!!!!!!!!!!!! #
colors:
  - YELLOW
  - BLUE
  - GREEN
  - AQUA
  - RED
  - LIGHT_PURPLE
  - WHITE
  - GOLD
  - BLACK
  - DARK_BLUE
  - DARK_GREEN
  - DARK_AQUA
  - DARK_RED
  - DARK_PURPLE
  - GRAY
  - DARK_GRAY

# Play sound when view GUI opens.
# You can find all the sounds here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
sound:
  # Play or not, default enabled.
  enable: true
  open_sound: BLOCK_BARREL_OPEN
  close_sound: BLOCK_BARREL_CLOSE

# Custom permission for the plugin.
permissions:
  use: containerview.use
  reload: containerview.reload

# Print debug messages in console.
debug: false



